<a href="https://colab.research.google.com/github/Ak759-wq/NLP-project/blob/main/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install datasets

Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.29.4)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.7.1)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (1.22.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.14.1)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.6.17)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2026.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.24.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (4.14.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

In [2]:
from datasets import load_dataset
import pandas as pd

In [3]:
dataset = load_dataset("CShorten/ML-ArXiv-Papers", split="train")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [4]:
df = pd.DataFrame(dataset)
df.head()

,Unnamed: 0.1,Unnamed: 0,title,abstract
0,0,0.0,Learning from compressed observations,The problem of statistical learning is to co...
1,1,1.0,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun..."
2,2,2.0,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...
3,3,3.0,A neural network approach to ordinal regression,Ordinal regression is an important type of l...
4,4,4.0,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...

In [5]:
df = df[["title", "abstract"]]

In [6]:
df = df.head(15000)

In [7]:
df["paper_text"] = df["title"] + " " + df["abstract"]

In [8]:
df["paper_text"] = df["paper_text"].str.replace("\n", " ", regex=False)
df["paper_text"] = df["paper_text"].str.strip()

In [9]:
df["paper_text"].iloc[0]

'Learning from compressed observations   The problem of statistical learning is to construct a predictor of a random variable $Y$ as a function of a related random variable $X$ on the basis of an i.i.d. training sample from the joint distribution of $(X,Y)$. Allowable predictors are drawn from some specified class, and the goal is to approach asymptotically the performance (expected loss) of the best predictor in the class. We consider the setting in which one has perfect observation of the $X$-part of the sample, while the $Y$-part has to be communicated at some finite bit rate. The encoding of the $Y$-values is allowed to depend on the $X$-values. Under suitable regularity conditions on the admissible predictors, the underlying family of probability distributions and the loss function, we give an information-theoretic characterization of achievable predictor performance in terms of conditional distortion-rate functions. The ideas are illustrated on the example of nonparametric regression in Gaussian noise.'

In [10]:
df.shape

(15000, 3)

In [11]:
!pip install sentence-transformers

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.6.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.13.0)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.22.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.11.0+cpu)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.4)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.25.1)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.8.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.14.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.1.2)

In [12]:
from sentence_transformers import SentenceTransformer

In [13]:
model = SentenceTransformer("all-MiniLM-L6-v2")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

In [14]:
print(type(model))

<class 'sentence_transformers.sentence_transformer.model.SentenceTransformer'>

In [15]:
sample_text = df["paper_text"].iloc[0]
sample_text

'Learning from compressed observations   The problem of statistical learning is to construct a predictor of a random variable $Y$ as a function of a related random variable $X$ on the basis of an i.i.d. training sample from the joint distribution of $(X,Y)$. Allowable predictors are drawn from some specified class, and the goal is to approach asymptotically the performance (expected loss) of the best predictor in the class. We consider the setting in which one has perfect observation of the $X$-part of the sample, while the $Y$-part has to be communicated at some finite bit rate. The encoding of the $Y$-values is allowed to depend on the $X$-values. Under suitable regularity conditions on the admissible predictors, the underlying family of probability distributions and the loss function, we give an information-theoretic characterization of achievable predictor performance in terms of conditional distortion-rate functions. The ideas are illustrated on the example of nonparametric regression in Gaussian noise.'

In [16]:
df["paper_text"]=df["paper_text"].str.replace("/n"," ",regex=False)
df["paper_text"]=df["paper_text"].str.strip()

In [17]:
sample_embedding = model.encode(sample_text)

print(type(sample_embedding))
print(sample_embedding.shape)

<class 'numpy.ndarray'>
(384,)

In [18]:
sample_embedding[:20]

array([-0.1315641 , -0.00678266, -0.00367612,  0.03265158,  0.11219642,
        0.01227267,  0.09816719, -0.0900523 ,  0.04231161, -0.01977348,
       -0.03308417,  0.07452948,  0.10632038, -0.02060429, -0.02052106,
        0.00169493,  0.07081953,  0.05854454, -0.11231912,  0.02082474],
      dtype=float32)

In [19]:
sample_embeddings = model.encode(df["paper_text"].head(5).tolist())

In [20]:
sample_embeddings.shape

(5, 384)

In [21]:
from sklearn.metrics.pairwise import cosine_similarity

In [22]:
similarity = cosine_similarity(
    sample_embeddings[0].reshape(1, -1),
    sample_embeddings[0].reshape(1, -1)
)

print(similarity)

[[1.0000001]]

In [23]:
similarity = cosine_similarity(
    sample_embeddings[0].reshape(1, -1),
    sample_embeddings[1].reshape(1, -1)
)

print(similarity)

[[0.36625272]]

In [24]:
for i in range(1, 5):

    similarity = cosine_similarity(
        sample_embeddings[0].reshape(1, -1),
        sample_embeddings[i].reshape(1, -1)
    )

    print(f"Paper {i} Similarity:", similarity[0][0])

Paper 1 Similarity: 0.36625272
Paper 2 Similarity: 0.33522844
Paper 3 Similarity: 0.15505108
Paper 4 Similarity: 0.37421533

In [25]:
df["paper_text"] = df["title"] + " " + df["abstract"]
df["paper_text"] = df["paper_text"].str.replace("\n", " ", regex=False)
df["paper_text"] = df["paper_text"].str.strip()

embeddings = model.encode(
    df["paper_text"].tolist(),
    batch_size=32,
    show_progress_bar=True
)

Batches:   0%|          | 0/469 [00:00<?, ?it/s]

In [26]:
print(type(embeddings))
print(embeddings.shape)
print(embeddings.dtype)

<class 'numpy.ndarray'>
(15000, 384)
float32

In [27]:
import os
import numpy as np

In [28]:
if os.path.exists("paper_embeddings.npy"):
    print("Loading saved embeddings...")
    embeddings = np.load("paper_embeddings.npy")
else:
    print("Generating embeddings...")
    embeddings = model.encode(
        df["paper_text"].tolist(),
        batch_size=32,
        show_progress_bar=True
    )
    np.save("paper_embeddings.npy", embeddings)
    print("Embeddings saved successfully!")

Loading saved embeddings...

In [29]:
print(type(embeddings))
print(embeddings.shape)
print(embeddings.dtype)

<class 'numpy.ndarray'>
(15000, 384)
float32

In [30]:
!pip install faiss-cpu

Requirement already satisfied: faiss-cpu in /usr/local/lib/python3.12/dist-packages (1.14.3)
Requirement already satisfied: numpy>=1.25 in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (26.2)

In [31]:
import faiss

In [32]:
faiss.normalize_L2(embeddings)

In [33]:
index = faiss.IndexFlatIP(embeddings.shape[1])

In [34]:
index.add(embeddings)

In [35]:
print(index.ntotal)

15000

In [36]:
query = "Deep learning for medical image analysis"

In [37]:
query_embedding = model.encode([query])
query_embedding.shape

(1, 384)

In [38]:
faiss.normalize_L2(query_embedding)

In [39]:
D, I = index.search(query_embedding, 5)

print(D)
print(I)

[[0.6807244  0.67092204 0.65219975 0.62811744 0.61311525]]
[[10466 13730 11873 12691 11282]]

In [40]:
for score, idx in zip(D[0], I[0]):
    print("Title:", df.iloc[idx]["title"])
    print("Abstract:", df.iloc[idx]["abstract"][:300])
    print("Similarity Score:", round(score, 4))
    print("-" * 80)

Title: A Perspective on Deep Imaging
Abstract:   The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image

Similarity Score: 0.6807
--------------------------------------------------------------------------------
Title: Convolutional Neural Networks for Medical Image Analysis: Full Training
  or Fine Tuning?
Abstract:   Training a deep convolutional neural network (CNN) from scratch is difficult
because it requires a large amount of labeled training data and a great deal of
expertise to ensure proper convergence. A promising alternative is to fine-tune
a CNN that has been pre-trained using, for instance, a large
Similarity Score: 0.6709
--------------------------------------------------------------------------------
Title: Classification of MRI data using Deep Learning and Gaussian
  Process-based Model Selection
Abstract:   The classification of MRI images according to the anatomical field of view is
a necessary task to solve when faced with the increasing quantity of medical
images. In parallel, advances in deep learning makes it a suitable tool for
computer vision problems. Using a common architecture (such as Alex
Similarity Score: 0.6522
--------------------------------------------------------------------------------
Title: High-Resolution Breast Cancer Screening with Multi-View Deep
  Convolutional Neural Networks
Abstract:   Advances in deep learning for natural images have prompted a surge of
interest in applying similar techniques to medical images. The majority of the
initial attempts focused on replacing the input of a deep convolutional neural
network with a medical image, which does not take into consideration t
Similarity Score: 0.6281
--------------------------------------------------------------------------------
Title: Deep Learning for the Classification of Lung Nodules
Abstract:   Deep learning, as a promising new area of machine learning, has attracted a
rapidly increasing attention in the field of medical imaging. Compared to the
conventional machine learning methods, deep learning requires no hand-tuned
feature extractor, and has shown a superior performance in many visu
Similarity Score: 0.6131
--------------------------------------------------------------------------------

In [41]:
import time

start = time.time()
D, I = index.search(query_embedding, 5)
end = time.time()

print(f"Search Time: {end-start:.4f} seconds")

Search Time: 0.0052 seconds

In [42]:
def search_paper(query, k=5):

    query_embedding = model.encode([query])
    faiss.normalize_L2(query_embedding)

    D, I = index.search(query_embedding, k)

    for score, idx in zip(D[0], I[0]):
        print("Title:", df.iloc[idx]["title"])
        print("Abstract:", df.iloc[idx]["abstract"][:300])
        print("Similarity Score:", round(score, 4))
        print("-" * 80)

    return D, I

In [43]:
search_paper("Deep learning for medical image analysis")

Title: A Perspective on Deep Imaging
Abstract:   The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image

Similarity Score: 0.6807
--------------------------------------------------------------------------------
Title: Convolutional Neural Networks for Medical Image Analysis: Full Training
  or Fine Tuning?
Abstract:   Training a deep convolutional neural network (CNN) from scratch is difficult
because it requires a large amount of labeled training data and a great deal of
expertise to ensure proper convergence. A promising alternative is to fine-tune
a CNN that has been pre-trained using, for instance, a large
Similarity Score: 0.6709
--------------------------------------------------------------------------------
Title: Classification of MRI data using Deep Learning and Gaussian
  Process-based Model Selection
Abstract:   The classification of MRI images according to the anatomical field of view is
a necessary task to solve when faced with the increasing quantity of medical
images. In parallel, advances in deep learning makes it a suitable tool for
computer vision problems. Using a common architecture (such as Alex
Similarity Score: 0.6522
--------------------------------------------------------------------------------
Title: High-Resolution Breast Cancer Screening with Multi-View Deep
  Convolutional Neural Networks
Abstract:   Advances in deep learning for natural images have prompted a surge of
interest in applying similar techniques to medical images. The majority of the
initial attempts focused on replacing the input of a deep convolutional neural
network with a medical image, which does not take into consideration t
Similarity Score: 0.6281
--------------------------------------------------------------------------------
Title: Deep Learning for the Classification of Lung Nodules
Abstract:   Deep learning, as a promising new area of machine learning, has attracted a
rapidly increasing attention in the field of medical imaging. Compared to the
conventional machine learning methods, deep learning requires no hand-tuned
feature extractor, and has shown a superior performance in many visu
Similarity Score: 0.6131
--------------------------------------------------------------------------------

(array([[0.6807244 , 0.67092204, 0.65219975, 0.62811744, 0.61311525]],
       dtype=float32),
 array([[10466, 13730, 11873, 12691, 11282]]))

In [44]:
!pip install --upgrade transformers

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.13.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.22.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.25.1)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.29.4)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.14.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)

In [1]:
# Explicitly uninstall and reinstall transformers and its dependencies for a clean setup.
# This ensures the correct versions are on disk and includes 'accelerate' as a common dependency.
!pip uninstall -y transformers huggingface-hub tokenizers accelerate
!pip install transformers==5.13.0 huggingface-hub==1.22.0 tokenizers==0.22.2 accelerate

from transformers import pipeline

try:
    summarizer = pipeline(
        task="summarization",
        model="facebook/bart-large-cnn",
    )
except KeyError as e:
    print(f"Caught an error: {e}")
    print("It seems the 'summarization' task is not recognized by the `transformers` library.")
    print("This usually happens when the Python environment hasn't fully reloaded the newly installed packages.")
    print("Or, a critical dependency like 'accelerate' might be missing or incorrectly installed.")
    print("\n**********************************************************************************")
    print("** PLEASE RESTART THE COLAB RUNTIME (Runtime -> Restart runtime) AND THEN RERUN THIS CELL. **")
    print("**********************************************************************************")
    summarizer = None # Set summarizer to None to indicate failure
except Exception as e:
    print(f"An unexpected error occurred: {e}")
    summarizer = None

Found existing installation: transformers 5.13.0
Uninstalling transformers-5.13.0:
  Successfully uninstalled transformers-5.13.0
Found existing installation: huggingface_hub 1.22.0
Uninstalling huggingface_hub-1.22.0:
  Successfully uninstalled huggingface_hub-1.22.0
Found existing installation: tokenizers 0.22.2
Uninstalling tokenizers-0.22.2:
  Successfully uninstalled tokenizers-0.22.2
Found existing installation: accelerate 1.14.0
Uninstalling accelerate-1.14.0:
  Successfully uninstalled accelerate-1.14.0
Collecting transformers==5.13.0
  Using cached transformers-5.13.0-py3-none-any.whl.metadata (32 kB)
Collecting huggingface-hub==1.22.0
  Using cached huggingface_hub-1.22.0-py3-none-any.whl.metadata (14 kB)
Collecting tokenizers==0.22.2
  Using cached tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.3 kB)
Collecting accelerate
  Using cached accelerate-1.14.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers==5.13.0) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers==5.13.0) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers==5.13.0) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers==5.13.0) (2025.11.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers==5.13.0) (0.25.1)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from transformers==5.13.0) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in /usr/local/lib/python3.12/dist-packages (from transformers==5.13.0) (4.67.3)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub==1.22.0) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub==1.22.0) (3.29.4)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub==1.22.0) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub==1.22.0) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub==1.22.0) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub==1.22.0) (4.15.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.11.0+cpu)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub==1.22.0) (4.14.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub==1.22.0) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub==1.22.0) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub==1.22.0) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub==1.22.0) (0.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers==5.13.0) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers==5.13.0) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers==5.13.0) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers==5.13.0) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers==5.13.0) (2.20.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers==5.13.0) (0.1.2)
Using cached transformers-5.13.0-py3-none-any.whl (11.5 MB)
Using cached huggingface_hub-1.22.0-py3-none-any.whl (765 kB)
Using cached tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
Using cached accelerate-1.14.0-py3-none-any.whl (389 kB)
Installing collected packages: huggingface-hub, tokenizers, accelerate, transformers
Successfully installed accelerate-1.14.0 huggingface-hub-1.22.0 tokenizers-0.22.2 transformers-5.13.0

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Caught an error: "Unknown task summarization, available tasks are ['any-to-any', 'audio-classification', 'automatic-speech-recognition', 'depth-estimation', 'document-question-answering', 'feature-extraction', 'fill-mask', 'image-classification', 'image-feature-extraction', 'image-segmentation', 'image-text-to-text', 'keypoint-matching', 'mask-generation', 'ner', 'object-detection', 'sentiment-analysis', 'table-question-answering', 'text-classification', 'text-generation', 'text-to-audio', 'text-to-speech', 'token-classification', 'video-classification', 'zero-shot-audio-classification', 'zero-shot-classification', 'zero-shot-image-classification', 'zero-shot-object-detection']"
It seems the 'summarization' task is not recognized by the `transformers` library.
This usually happens when the Python environment hasn't fully reloaded the newly installed packages.
Or, a critical dependency like 'accelerate' might be missing or incorrectly installed.

**********************************************************************************
** PLEASE RESTART THE COLAB RUNTIME (Runtime -> Restart runtime) AND THEN RERUN THIS CELL. **
**********************************************************************************

In [2]:
type(summarizer)

NoneType

In [3]:
from transformers import pipeline

try:
    summarizer = pipeline(
        "summarization",
        model="facebook/bart-large-cnn"
    )
except KeyError as e:
    print(f"Caught an error: {e}")
    print("It seems the 'summarization' task is not recognized by the `transformers` library.")
    print("This usually happens when the Python environment hasn't fully reloaded the newly installed packages.")
    print("\n**********************************************************************************")
    print("** PLEASE RESTART THE COLAB RUNTIME (Runtime -> Restart runtime) AND THEN RERUN ALL CELLS. **")
    print("**********************************************************************************")
    summarizer = None # Ensure summarizer is None if initialization fails
except Exception as e:
    print(f"An unexpected error occurred: {e}")
    summarizer = None

Caught an error: "Unknown task summarization, available tasks are ['any-to-any', 'audio-classification', 'automatic-speech-recognition', 'depth-estimation', 'document-question-answering', 'feature-extraction', 'fill-mask', 'image-classification', 'image-feature-extraction', 'image-segmentation', 'image-text-to-text', 'keypoint-matching', 'mask-generation', 'ner', 'object-detection', 'sentiment-analysis', 'table-question-answering', 'text-classification', 'text-generation', 'text-to-audio', 'text-to-speech', 'token-classification', 'video-classification', 'zero-shot-audio-classification', 'zero-shot-classification', 'zero-shot-image-classification', 'zero-shot-object-detection']"
It seems the 'summarization' task is not recognized by the `transformers` library.
This usually happens when the Python environment hasn't fully reloaded the newly installed packages.

**********************************************************************************
** PLEASE RESTART THE COLAB RUNTIME (Runtime -> Restart runtime) AND THEN RERUN ALL CELLS. **
**********************************************************************************

In [5]:
if 'df' not in globals():
    print("Error: DataFrame 'df' is not defined. Please rerun all cells from the beginning after a runtime restart if needed.")
    summary = None
elif summarizer is None:
    print("Error: The 'summarizer' pipeline is not initialized. This often happens when the Python environment hasn't fully reloaded the newly installed packages.\n")
    print("**********************************************************************************")
    print("** PLEASE RESTART THE COLAB RUNTIME (Runtime -> Restart runtime) AND THEN RERUN ALL CELLS. **")
    print("**********************************************************************************")
    summary = None
else:
    try:
        summary = summarizer(df.iloc[10466]["abstract"], max_length=120 , min_length=40)
        print(summary)
    except Exception as e:
        print(f"An error occurred during summarization: {e}")
        summary = None

Error: DataFrame 'df' is not defined. Please rerun all cells from the beginning after a runtime restart if needed.

In [6]:
type(summary)

NoneType

In [8]:
if summary is not None and len(summary) > 0:
    print(type(summary[0]))
else:
    print("The 'summary' variable is not properly initialized or is empty.")
    print("This indicates that the 'summarizer' pipeline likely failed to initialize earlier, or the 'df' DataFrame was not loaded.")
    print("\n**********************************************************************************")
    print("** PLEASE RESTART THE COLAB RUNTIME (Runtime -> Restart runtime) AND THEN RERUN ALL CELLS FROM THE BEGINNING. **")
    print("**********************************************************************************")

The 'summary' variable is not properly initialized or is empty.
This indicates that the 'summarizer' pipeline likely failed to initialize earlier, or the 'df' DataFrame was not loaded.

**********************************************************************************
** PLEASE RESTART THE COLAB RUNTIME (Runtime -> Restart runtime) AND THEN RERUN ALL CELLS FROM THE BEGINNING. **
**********************************************************************************

In [10]:
if summary is not None and len(summary) > 0:
    print(summary[0]["summary_text"])
else:
    print("The 'summary' variable is not properly initialized or is empty.")
    print("This indicates that the 'summarizer' pipeline likely failed to initialize earlier.")
    print("\n**********************************************************************************")
    print("** PLEASE RESTART THE COLAB RUNTIME (Runtime -> Restart runtime) AND THEN RERUN ALL CELLS FROM THE BEGINNING. **")
    print("**********************************************************************************")

The 'summary' variable is not properly initialized or is empty.
This indicates that the 'summarizer' pipeline likely failed to initialize earlier.

**********************************************************************************
** PLEASE RESTART THE COLAB RUNTIME (Runtime -> Restart runtime) AND THEN RERUN ALL CELLS FROM THE BEGINNING. **
**********************************************************************************

In [ ]:
for score,idx in zip(D[0],I[0]):
  print("Similarity score", score)
  print("Title",df.iloc[idx]["title"])
  print("Abstract",df.iloc[idx]["abstract"][:500])

  summary = summarizer(df.iloc[idx]["abstract"], max_length=120 , min_length=40)
  print(summary)
  print(summary[0]["summary_text"])
  print()

In [73]:
def search_and_summarize(query , k=5):
  query_embedding = model.encode([query])
  faiss.normalize_L2(query_embedding)
  D,I=index.search(query_embedding,k)
  for score,idx in zip(D[0],I[0]):
    print("Similarity score", score)
    print("Title",df.iloc[idx]["title"])
    print("Abstract",df.iloc[idx]["abstract"][:500])
    print()

  summary = summarizer(df.iloc[idx]["abstract"], max_length=120 , min_length=40 , do_sample=False)
  print(summary)
  print(summary[0]["summary_text"])
  print()

In [ ]:
search_and_summarize("Deep learning in medical imaging", k=5)

In [ ]:
pip install keybert==0.8.5

In [ ]:
from keybert import KeyBERT

In [ ]:
kw_model = KeyBERT(model)

In [ ]:
type(kw_model)

In [ ]:
print(df.iloc[10466]["abstract"])

In [ ]:
text =df.iloc[10466]["abstract"]
keywords = kw_model.extract_keywords(text)

In [ ]:
print(keywords)
print(type(keywords))
print(type(keywords[0]))

In [ ]:
keywords = kw_model.extract_keywords(text , keyphrase_ngram_range=(1,3), stop_words="english")

In [72]:
print(keywords)

NameError: name 'keywords' is not defined

In [63]:
def search_and_summarize(query , k=5):
  query_embedding = model.encode([query])
  faiss.normalize_L2(query_embedding)
  D,I=index.search(query_embedding,k)
  for score,idx in zip(D[0],I[0]):
    print("Similarity score", score)
    print("Title",df.iloc[idx]["title"])
    print("Abstract",df.iloc[idx]["abstract"][:500])
    print()
  summary = summarizer(df.iloc[idx]["abstract"], max_length=120 , min_length=40 , do_sample=False)
  print(summary)
  print(summary[0]["summary_text"])
  print()
  keywords = kw_model.extract_keywords(text , keyphrase_ngram_range=(1,3), stop_words="english")
  print(keywords)
  for k,s in keywords:
    print(k)
  print()

NER(Named Entity Recognition)

In [61]:
!pip install -q spacy
!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 64.8 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [62]:
print(df.shape)

(15000, 3)

In [64]:
len(df)

15000

In [65]:
import pandas as pd
import spacy

In [66]:
nlp = spacy.load("en_core_web_sm")

In [67]:
def extract_entities(text):
    if pd.isna(text):
        return []

    text = str(text)

    doc = nlp(text)

    return [(ent.text, ent.label_) for ent in doc.ents]

In [68]:
sample_df = df.head(500).copy()

In [69]:
from datasets import load_dataset

# Check if df exists and has the 'abstract' column from the original dataset
# If not, re-initialize df and sample_df from the ML-ArXiv-Papers dataset
if 'abstract' not in df.columns or df.shape[0] != 15000:
    print("Re-initializing df with original paper data...")
    dataset = load_dataset("CShorten/ML-ArXiv-Papers", split="train")
    df = pd.DataFrame(dataset)
    df = df[["title", "abstract"]]
    df = df.head(15000)
    df["paper_text"] = df["title"] + " " + df["abstract"]
    df["paper_text"] = df["paper_text"].str.replace("\n", " ", regex=False)
    df["paper_text"] = df["paper_text"].str.strip()
    sample_df = df.head(500).copy()

# Now apply the extract_entities function to the 'abstract' column
sample_df["Entities"] = sample_df["abstract"].apply(extract_entities)
print("Entities extracted successfully for sample_df!")
print(sample_df.head())

Entities extracted successfully for sample_df!
                                               title  \
0              Learning from compressed observations
1  Sensor Networks with Random Links: Topology De...
2  The on-line shortest path problem under partia...
3    A neural network approach to ordinal regression
4   Parametric Learning and Monte Carlo Optimization

                                            abstract  \
0    The problem of statistical learning is to co...
1    In a sensor network, in practice, the commun...
2    The on-line shortest path problem is conside...
3    Ordinal regression is an important type of l...
4    This paper uncovers and explores the close r...

                                          paper_text  \
0  Learning from compressed observations   The pr...
1  Sensor Networks with Random Links: Topology De...
2  The on-line shortest path problem under partia...
3  A neural network approach to ordinal regressio...
4  Parametric Learning and Monte Carlo Optimizati...

                                            Entities
0  [(X$, MONEY), (X$-part, MONEY), (Y$-part, PERS...
1  [(3, CARDINAL), (SNR, ORG), (SNR, ORG), (1, CA...
2           [(two, CARDINAL), (1/\sqrt{n, CARDINAL)]
3  [(NNRank, ORG), (Gaussian, NORP), (NNRank, ORG...
4  [(Monte Carlo\nOptimization, PERSON), (MCO, OR...

In [70]:
sample_df[["title", "Entities"]].head(10)

,title,Entities
0,Learning from compressed observations,"[(X$, MONEY), (X$-part, MONEY), (Y$-part, PERS..."
1,Sensor Networks with Random Links: Topology De...,"[(3, CARDINAL), (SNR, ORG), (SNR, ORG), (1, CA..."
2,The on-line shortest path problem under partia...,"[(two, CARDINAL), (1/\sqrt{n, CARDINAL)]"
3,A neural network approach to ordinal regression,"[(NNRank, ORG), (Gaussian, NORP), (NNRank, ORG..."
4,Parametric Learning and Monte Carlo Optimization,"[(Monte Carlo\nOptimization, PERSON), (MCO, OR..."
5,Preconditioned Temporal Difference Learning,"[(english, LANGUAGE), (ICML, ORG)]"
6,A Note on the Inapproximability of Correlation...,"[(two, CARDINAL), (MaxAgree, ORG), (MinDisagre..."
7,Joint universal lossy coding and identificatio...,"[(Rissanen, GPE), (Vapnik-Chervonenkis, ORG)]"
8,Supervised Feature Selection via Dependence Es...,"[(Hilbert-Schmidt Independence Criterion, ORG)..."
9,Equivalence of LP Relaxation and Max-Product f...,"[(Max, PERSON), (max, PERSON), (first, ORDINAL..."

In [71]:
sample_df.to_csv("research_papers_with_entities.csv", index=False)

print("NER completed successfully!")
print("Processed Papers:", len(sample_df))

NER completed successfully!
Processed Papers: 500

similar paper recommendation

In [58]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import os
from sentence_transformers import SentenceTransformer
import pandas as pd
from datasets import load_dataset
import faiss # Ensure faiss is imported for global usage, or import locally if preferred

def similar_papers(index, top_n=5):
    global embeddings, model, df # Declare intent to use global variables

    print("--- Executing similar_papers function ---")

    # Ensure model is initialized if not already
    if 'model' not in globals() or not isinstance(model, SentenceTransformer):
        print("Initializing SentenceTransformer model inside similar_papers...")
        model = SentenceTransformer("all-MiniLM-L6-v2")

    # Ensure df is properly loaded if not already
    if 'df' not in globals() or not isinstance(df, pd.DataFrame) or 'paper_text' not in df.columns or df.shape[0] != 15000:
        print("Re-initializing df with original paper data inside similar_papers...")
        dataset = load_dataset("CShorten/ML-ArXiv-Papers", split="train")
        df = pd.DataFrame(dataset)
        df = df[["title", "abstract"]]
        df = df.head(15000)
        df["paper_text"] = df["title"] + " " + df["abstract"]
        df["paper_text"] = df["paper_text"].str.replace("\n", " ", regex=False)
        df["paper_text"] = df["paper_text"].str.strip()

    # Ensure embeddings are loaded or generated
    if 'embeddings' not in globals() or not isinstance(embeddings, np.ndarray) or embeddings.shape[0] != df.shape[0]:
        print("Embeddings not found in global scope or corrupted. Attempting to load or regenerate inside similar_papers...")
        if os.path.exists("paper_embeddings.npy"):
            try:
                loaded_embeddings = np.load("paper_embeddings.npy")
                if loaded_embeddings.shape[0] == df.shape[0]:
                    embeddings = loaded_embeddings
                    print("Embeddings loaded successfully from file.")
                else:
                    raise ValueError(f"Mismatch in embedding size: expected {df.shape[0]}, got {loaded_embeddings.shape[0]}")
            except (FileNotFoundError, ValueError, Exception) as e:
                print(f"Error loading embeddings from file ({e}). Regenerating embeddings...")
                embeddings = model.encode(
                    df["paper_text"].tolist(),
                    batch_size=32,
                    show_progress_bar=True
                )
                np.save("paper_embeddings.npy", embeddings)
                print("Embeddings regenerated and saved successfully!")
        else:
            print("paper_embeddings.npy not found. Generating embeddings...")
            embeddings = model.encode(
                df["paper_text"].tolist(),
                batch_size=32,
                show_progress_bar=True
            )
            np.save("paper_embeddings.npy", embeddings)
            print("Embeddings generated and saved successfully!")

    # It's crucial that faiss is available. We'll import it here to be safe.
    # faiss.normalize_L2 modifies in-place.
    faiss.normalize_L2(embeddings)

    similarity = cosine_similarity(
        [embeddings[index]],
        embeddings
    )[0]

    similar = similarity.argsort()[::-1][1:top_n+1]

    return df.iloc[similar][["title"]]

similar_papers(0)

--- Executing similar_papers function ---

                                                   title
208    Achievability results for statistical learning...
9237   Rate-Distortion Bounds on Bayes Risk in Superv...
2980   Sparse Signal Processing with Linear and Nonli...
10270  Uniform Generalization, Concentration, and Ada...
10749  On statistical learning via the lens of compre...